version: "3"

services:
  snake-main:
    build:
      context: .
    ports:
      - "8081:8081"
    expose: 
      - 8081
  gameserver:
    image: sendwithus/battlesnake-server
    ports:
      - "3000:3000"
